
/******************************************************************************
 * This file has been generated by Module Structure Generator
 * 2082 - Hau Sy Le - hau.le.eb@renesas.com
 ******************************************************************************
 * File name:		swdt.h
 * Date created:	11/1/2018 2:55:30 PM
 * PC name:			RVC-LT-410219
 * User name:		haule2
******************************************************************************/

#ifndef	SWDT_H_
#define	SWDT_H_

#include	<stdint.h>

/******************************************************************************
 *	Name	Offset	Size	R/W
 ******************************************************************************
 *	SWTCNT	0x0	32	RW
 *	SWTCSRA	0x4	32	RW
 *	SWTCSRB	0x8	32	RW
******************************************************************************/
typedef struct
{
	union
	{
		/* Name:	SWTCNT
		 * Offset:	0x0
		 * Size:	32 bits */
		__RW	uint32_t	SWTCNT;
	};

	union
	{
		/* Name:	SWTCSRA
		 * Offset:	0x4
		 * Size:	32 bits */
		__RW	uint32_t	SWTCSRA;
		struct
		{
			__RW	uint32_t	CKS0	:3;
			__RW	uint32_t	WOVFE	:1;
			__RW	uint32_t	WOVF	:1;
			__RW	uint32_t	WRFLG	:1;
			__RW	uint32_t	TME	:1;
		};
	};

	union
	{
		/* Name:	SWTCSRB
		 * Offset:	0x8
		 * Size:	32 bits */
		__RW	uint32_t	SWTCSRB;
		struct
		{
			__RW	uint32_t	CKS1	:6;
		};
	};

} SWDT_t;

#define SWDT_CNT_PASSWORD   0x5a5a0000
#define SWDT_CSRA_PASSWORD  0xa5a5a500
#define SWDT_CSRB_PASSWORD  0xa5a5a500

#endif	/* SWDT_H_ */

