	
;-------------------------------------------------------------------------------
;	
;	File:			i2c0.s
;	Purpose:		Register definition for module I2C0
;	Compatibility:	ARM
;	Date created:	05/22/2018 09:51:44 AM
;	
;	This source code is generated by TM Creator, written by 2082 - Hau Sy Le.
;	If you found any bug, please feedback to me at hau.le.eb@rvc.renesas.com
;	Your feedback is very valuable.
;	
;-------------------------------------------------------------------------------

I2C0_ICSCR	EQU	0xE6500000
I2C0_ICMCR	EQU	0xE6500004
I2C0_ICSSR	EQU	0xE6500008
I2C0_ICMSR	EQU	0xE650000C
I2C0_ICSIER	EQU	0xE6500010
I2C0_ICMIER	EQU	0xE6500014
I2C0_ICCCR	EQU	0xE6500018
I2C0_ICSAR	EQU	0xE650001C
I2C0_ICMAR	EQU	0xE6500020
I2C0_ICxXD	EQU	0xE6500024
I2C0_ICCCR2	EQU	0xE6500028
I2C0_ICMPR	EQU	0xE650002C
I2C0_ICHPR	EQU	0xE6500030
I2C0_ICLPR	EQU	0xE6500034
I2C0_ICFBSCR	EQU	0xE6500038
I2C0_ICDMAER	EQU	0xE650003C
		
	END
	
