	
;-------------------------------------------------------------------------------
;	
;	File:			i2c1.s
;	Purpose:		Register definition for module I2C1
;	Compatibility:	ARM
;	Date created:	05/25/2018 03:54:37 PM
;	
;	This source code is generated by TM Creator, written by 2082 - Hau Sy Le.
;	If you found any bug, please feedback to me at hau.le.eb@rvc.renesas.com
;	Your feedback is very valuable.
;	
;-------------------------------------------------------------------------------

I2C1_ICSCR	EQU	0xE6508000
I2C1_ICMCR	EQU	0xE6508004
I2C1_ICSSR	EQU	0xE6508008
I2C1_ICMSR	EQU	0xE650800C
I2C1_ICSIER	EQU	0xE6508010
I2C1_ICMIER	EQU	0xE6508014
I2C1_ICCCR	EQU	0xE6508018
I2C1_ICSAR	EQU	0xE650801C
I2C1_ICMAR	EQU	0xE6508020
I2C1_ICxXD	EQU	0xE6508024
I2C1_ICCCR2	EQU	0xE6508028
I2C1_ICMPR	EQU	0xE650802C
I2C1_ICHPR	EQU	0xE6508030
I2C1_ICLPR	EQU	0xE6508034
I2C1_ICFBSCR	EQU	0xE6508038
I2C1_ICDMAER	EQU	0xE650803C
		
	END
	
