	
;-------------------------------------------------------------------------------
;	
;	File:			i2c2.s
;	Purpose:		Register definition for module I2C2
;	Compatibility:	ARM
;	Date created:	05/25/2018 03:56:04 PM
;	
;	This source code is generated by TM Creator, written by 2082 - Hau Sy Le.
;	If you found any bug, please feedback to me at hau.le.eb@rvc.renesas.com
;	Your feedback is very valuable.
;	
;-------------------------------------------------------------------------------

I2C2_ICSCR	EQU	0xE6510000
I2C2_ICMCR	EQU	0xE6510004
I2C2_ICSSR	EQU	0xE6510008
I2C2_ICMSR	EQU	0xE651000C
I2C2_ICSIER	EQU	0xE6510010
I2C2_ICMIER	EQU	0xE6510014
I2C2_ICCCR	EQU	0xE6510018
I2C2_ICSAR	EQU	0xE651001C
I2C2_ICMAR	EQU	0xE6510020
I2C2_ICxXD	EQU	0xE6510024
I2C2_ICCCR2	EQU	0xE6510028
I2C2_ICMPR	EQU	0xE651002C
I2C2_ICHPR	EQU	0xE6510030
I2C2_ICLPR	EQU	0xE6510034
I2C2_ICFBSCR	EQU	0xE6510038
I2C2_ICDMAER	EQU	0xE651003C
		
	END
	
