	
;-------------------------------------------------------------------------------
;	
;	File:			i2c3.s
;	Purpose:		Register definition for module I2C3
;	Compatibility:	ARM
;	Date created:	05/25/2018 03:56:44 PM
;	
;	This source code is generated by TM Creator, written by 2082 - Hau Sy Le.
;	If you found any bug, please feedback to me at hau.le.eb@rvc.renesas.com
;	Your feedback is very valuable.
;	
;-------------------------------------------------------------------------------

I2C3_ICSCR	EQU	0xE66D0000
I2C3_ICMCR	EQU	0xE66D0004
I2C3_ICSSR	EQU	0xE66D0008
I2C3_ICMSR	EQU	0xE66D000C
I2C3_ICSIER	EQU	0xE66D0010
I2C3_ICMIER	EQU	0xE66D0014
I2C3_ICCCR	EQU	0xE66D0018
I2C3_ICSAR	EQU	0xE66D001C
I2C3_ICMAR	EQU	0xE66D0020
I2C3_ICxXD	EQU	0xE66D0024
I2C3_ICCCR2	EQU	0xE66D0028
I2C3_ICMPR	EQU	0xE66D002C
I2C3_ICHPR	EQU	0xE66D0030
I2C3_ICLPR	EQU	0xE66D0034
I2C3_ICFBSCR	EQU	0xE66D0038
I2C3_ICDMAER	EQU	0xE66D003C
		
	END
	
