	
;-------------------------------------------------------------------------------
;	
;	File:			i2c4.s
;	Purpose:		Register definition for module I2C4
;	Compatibility:	ARM
;	Date created:	05/25/2018 03:57:05 PM
;	
;	This source code is generated by TM Creator, written by 2082 - Hau Sy Le.
;	If you found any bug, please feedback to me at hau.le.eb@rvc.renesas.com
;	Your feedback is very valuable.
;	
;-------------------------------------------------------------------------------

I2C4_ICSCR	EQU	0xE66D8000
I2C4_ICMCR	EQU	0xE66D8004
I2C4_ICSSR	EQU	0xE66D8008
I2C4_ICMSR	EQU	0xE66D800C
I2C4_ICSIER	EQU	0xE66D8010
I2C4_ICMIER	EQU	0xE66D8014
I2C4_ICCCR	EQU	0xE66D8018
I2C4_ICSAR	EQU	0xE66D801C
I2C4_ICMAR	EQU	0xE66D8020
I2C4_ICxXD	EQU	0xE66D8024
I2C4_ICCCR2	EQU	0xE66D8028
I2C4_ICMPR	EQU	0xE66D802C
I2C4_ICHPR	EQU	0xE66D8030
I2C4_ICLPR	EQU	0xE66D8034
I2C4_ICFBSCR	EQU	0xE66D8038
I2C4_ICDMAER	EQU	0xE66D803C
		
	END
	
