	
;-------------------------------------------------------------------------------
;	
;	File:			i2c5.s
;	Purpose:		Register definition for module I2C5
;	Compatibility:	ARM
;	Date created:	05/25/2018 04:03:48 PM
;	
;	This source code is generated by TM Creator, written by 2082 - Hau Sy Le.
;	If you found any bug, please feedback to me at hau.le.eb@rvc.renesas.com
;	Your feedback is very valuable.
;	
;-------------------------------------------------------------------------------

I2C5_ICSCR	EQU	0xE66E0000
I2C5_ICMCR	EQU	0xE66E0004
I2C5_ICSSR	EQU	0xE66E0008
I2C5_ICMSR	EQU	0xE66E000C
I2C5_ICSIER	EQU	0xE66E0010
I2C5_ICMIER	EQU	0xE66E0014
I2C5_ICCCR	EQU	0xE66E0018
I2C5_ICSAR	EQU	0xE66E001C
I2C5_ICMAR	EQU	0xE66E0020
I2C5_ICxXD	EQU	0xE66E0024
I2C5_ICCCR2	EQU	0xE66E0028
I2C5_ICMPR	EQU	0xE66E002C
I2C5_ICHPR	EQU	0xE66E0030
I2C5_ICLPR	EQU	0xE66E0034
I2C5_ICFBSCR	EQU	0xE66E0038
I2C5_ICDMAER	EQU	0xE66E003C
		
	END
	
