	
;-------------------------------------------------------------------------------
;	
;	File:			i2c6.s
;	Purpose:		Register definition for module I2C6
;	Compatibility:	ARM
;	Date created:	05/25/2018 04:04:18 PM
;	
;	This source code is generated by TM Creator, written by 2082 - Hau Sy Le.
;	If you found any bug, please feedback to me at hau.le.eb@rvc.renesas.com
;	Your feedback is very valuable.
;	
;-------------------------------------------------------------------------------

I2C6_ICSCR	EQU	0xE66E8000
I2C6_ICMCR	EQU	0xE66E8004
I2C6_ICSSR	EQU	0xE66E8008
I2C6_ICMSR	EQU	0xE66E800C
I2C6_ICSIER	EQU	0xE66E8010
I2C6_ICMIER	EQU	0xE66E8014
I2C6_ICCCR	EQU	0xE66E8018
I2C6_ICSAR	EQU	0xE66E801C
I2C6_ICMAR	EQU	0xE66E8020
I2C6_ICxXD	EQU	0xE66E8024
I2C6_ICCCR2	EQU	0xE66E8028
I2C6_ICMPR	EQU	0xE66E802C
I2C6_ICHPR	EQU	0xE66E8030
I2C6_ICLPR	EQU	0xE66E8034
I2C6_ICFBSCR	EQU	0xE66E8038
I2C6_ICDMAER	EQU	0xE66E803C
		
	END
	
