
/******************************************************************************
 * This file has been generated by Module Structure Generator
 * 2082 - Hau Sy Le - hau.le.eb@renesas.com
 ******************************************************************************
 * File name:		dmac.h
 * Date created:	10/17/2018 3:24:55 PM
 * PC name:			RVC-LT-410219
 * User name:		haule2
******************************************************************************/

#ifndef	DMAC_H_
#define	DMAC_H_

/* Standard C libraries */
#include <stdint.h>
#include <stdbool.h>

/* R-Car V3U drives */
#include <global.h>
#include <rcar_v3u/v3u.h>
#include <rcar_v3u/drivers/sim_utils.h>
#include <rcar_v3u/drivers/i2c.h>
#include <rcar_v3u/drivers/pfc.h>
#include <rcar_v3u/drivers/cpg.h>
#include <rcar_v3u/drivers/gic.h>
#include <rcar_v3u/drivers/dmac.h>
#include <rcar_v3u/drivers/kcrc.h>

#define DMARS_I2C0_MRX  0x90
#define DMARS_I2C0_MTX  0x91
#define DMARS_I2C1_MRX  0x92
#define DMARS_I2C1_MTX  0x93
#define DMARS_I2C2_MRX  0x94
#define DMARS_I2C2_MTX  0x95
#define DMARS_I2C3_MRX  0x96
#define DMARS_I2C3_MTX  0x97
#define DMARS_I2C4_MRX  0x98
#define DMARS_I2C4_MTX  0x99
#define DMARS_I2C5_MRX  0x9a
#define DMARS_I2C5_MTX  0x9b
#define DMARS_I2C6_MRX  0x9c
#define DMARS_I2C6_MTX  0x9d
#define DMARS_I2C0_SRX  0xa0
#define DMARS_I2C0_STX  0xa1
#define DMARS_I2C1_SRX  0xa2
#define DMARS_I2C1_STX  0xa3
#define DMARS_I2C2_SRX  0xa4
#define DMARS_I2C2_STX  0xa5
#define DMARS_I2C3_SRX  0xa6
#define DMARS_I2C3_STX  0xa7
#define DMARS_I2C4_SRX  0xa8
#define DMARS_I2C4_STX  0xa9
#define DMARS_I2C5_SRX  0xaa
#define DMARS_I2C5_STX  0xab
#define DMARS_I2C6_SRX  0xac
#define DMARS_I2C6_STX  0xad

/******************************************************************************
 *	Name			Offset	Size	R/W
 ******************************************************************************
 *	DMASAR			0x0		32		RW
 *	DMADAR			0x4		32		RW
 *	DMATCR			0x8		32		RW
 *	DMACHCR			0xC		32		RW
 *	DMAFIXSAR		0x10	32		RW
 *	DMAFIXDAR		0x14	32		RW
 *	DMATCRW			0x18	32		RW
 *	DMACHCRB		0x1C	32		RW
 *	DMASARS			0x20	32		RW
 *	DMADARS			0x24	32		RW
 *	DMATCRS			0x28	32		RW
 *	DMACHCRS		0x2C	32		RW
 *	DMATCRWS		0x38	32		RW
 *	DMARS			0x40	16		RW
 *	DMABUFCR		0x48	32		RW
 *	DMADPBASE		0x50	32		RW
 *	DMADPCR			0x54	32		RW
 *	DMADPEVTCR		0x58	32		RW
 *	DMADPEVTCNT		0x5C	32		RW
 *	DMAFIXDPBASE	0x60	32		RW
 *	DMAMMUSAR		0x68	32		RW
 *	MDAMMUDAR		0x6C	32		RW
 *	MDAERR			0x70	32		RW
 *	MDACACHE		0x74	32		RW
 *	DMAREGIONID		0x78	32		RW
 *	DMADEBUG		0x7C	32		RW
 *	DMACHID			0x80	32		RW
 *	DMASEC			0xB0	32		RW
 *	DMACHCLR		0x100	32		RW
******************************************************************************/
typedef struct
{
	union
	{
		/* Name:	DMASAR
		 * Offset:	0x0
		 * Size:	32 bits */
		__RW	uint32_t	DMASAR;

		/* Name:	SAR
		 * Offset:	0x0
		 * Size:	32 bits */
		__RW	uint32_t	SAR;
	};

	union
	{
		/* Name:	DMADAR
		 * Offset:	0x4
		 * Size:	32 bits */
		__RW	uint32_t	DMADAR;

		/* Name:	DAR
		 * Offset:	0x4
		 * Size:	32 bits */
		__RW	uint32_t	DAR;
	};

	union
	{
		/* Name:	DMATCR
		 * Offset:	0x8
		 * Size:	32 bits */
		__RW	uint32_t	DMATCR;
		struct
		{
			__RW	uint32_t	TCR	:24;
			__RO	uint32_t	DMATCR_RES_24	:1;
			__RO	uint32_t	DMATCR_RES_25	:1;
			__RO	uint32_t	DMATCR_RES_26	:1;
			__RO	uint32_t	DMATCR_RES_27	:1;
			__RO	uint32_t	DMATCR_RES_28	:1;
			__RO	uint32_t	DMATCR_RES_29	:1;
			__RO	uint32_t	DMATCR_RES_30	:1;
			__RO	uint32_t	DMATCR_RES_31	:1;
		};
	};

	union
	{
		/* Name:	DMACHCR
		 * Offset:	0xC
		 * Size:	32 bits */
		__RW	uint32_t	DMACHCR;
		struct
		{
			__RW	uint32_t	DE	:1;
			__RW	uint32_t	TE	:1;
			__RW	uint32_t	IE	:1;
			__RW	uint32_t	TS	:2;
			__RO	uint32_t	DMACHCR_RES_5	:1;
			__RO	uint32_t	DMACHCR_RES_6	:1;
			__RO	uint32_t	DMACHCR_RES_7	:1;
			__RW	uint32_t	RS	:4;
			__RW	uint32_t	SM	:2;
			__RW	uint32_t	DM	:2;
			__RO	uint32_t	DMACHCR_RES_16	:1;
			__RO	uint32_t	DMACHCR_RES_17	:1;
			__RW	uint32_t	DSIE	:1;
			__RW	uint32_t	DSE	:1;
			__RW	uint32_t	TS2	:2;
			__RW	uint32_t	DPB	:1;
			__RO	uint32_t	DMACHCR_RES_23	:1;
			__RW	uint32_t	RPT	:4;
			__RW	uint32_t	DPM	:2;
			__RW	uint32_t	CAIE	:1;
			__RW	uint32_t	CAE	:1;
		};

		/* Name:	CHCR
		 * Offset:	0xC
		 * Size:	32 bits */
		__RW	uint32_t	CHCR;
	};

	union
	{
		/* Name:	DMAFIXSAR
		 * Offset:	0x10
		 * Size:	32 bits */
		__RW	uint32_t	DMAFIXSAR;
		struct
		{
			__RW	uint32_t	FIXSAR	:8;
			__RO	uint32_t	DMAFIXSAR_RES_8	:1;
			__RO	uint32_t	DMAFIXSAR_RES_9	:1;
			__RO	uint32_t	DMAFIXSAR_RES_10	:1;
			__RO	uint32_t	DMAFIXSAR_RES_11	:1;
			__RO	uint32_t	DMAFIXSAR_RES_12	:1;
			__RO	uint32_t	DMAFIXSAR_RES_13	:1;
			__RO	uint32_t	DMAFIXSAR_RES_14	:1;
			__RO	uint32_t	DMAFIXSAR_RES_15	:1;
			__RO	uint32_t	DMAFIXSAR_RES_16	:1;
			__RO	uint32_t	DMAFIXSAR_RES_17	:1;
			__RO	uint32_t	DMAFIXSAR_RES_18	:1;
			__RO	uint32_t	DMAFIXSAR_RES_19	:1;
			__RO	uint32_t	DMAFIXSAR_RES_20	:1;
			__RO	uint32_t	DMAFIXSAR_RES_21	:1;
			__RO	uint32_t	DMAFIXSAR_RES_22	:1;
			__RO	uint32_t	DMAFIXSAR_RES_23	:1;
			__RO	uint32_t	DMAFIXSAR_RES_24	:1;
			__RO	uint32_t	DMAFIXSAR_RES_25	:1;
			__RO	uint32_t	DMAFIXSAR_RES_26	:1;
			__RO	uint32_t	DMAFIXSAR_RES_27	:1;
			__RO	uint32_t	DMAFIXSAR_RES_28	:1;
			__RO	uint32_t	DMAFIXSAR_RES_29	:1;
			__RO	uint32_t	DMAFIXSAR_RES_30	:1;
			__RO	uint32_t	DMAFIXSAR_RES_31	:1;
		};
	};

	union
	{
		/* Name:	DMAFIXDAR
		 * Offset:	0x14
		 * Size:	32 bits */
		__RW	uint32_t	DMAFIXDAR;
		struct
		{
			__RW	uint32_t	FIXDAR	:8;
			__RO	uint32_t	DMAFIXDAR_RES_8	:1;
			__RO	uint32_t	DMAFIXDAR_RES_9	:1;
			__RO	uint32_t	DMAFIXDAR_RES_10	:1;
			__RO	uint32_t	DMAFIXDAR_RES_11	:1;
			__RO	uint32_t	DMAFIXDAR_RES_12	:1;
			__RO	uint32_t	DMAFIXDAR_RES_13	:1;
			__RO	uint32_t	DMAFIXDAR_RES_14	:1;
			__RO	uint32_t	DMAFIXDAR_RES_15	:1;
			__RO	uint32_t	DMAFIXDAR_RES_16	:1;
			__RO	uint32_t	DMAFIXDAR_RES_17	:1;
			__RO	uint32_t	DMAFIXDAR_RES_18	:1;
			__RO	uint32_t	DMAFIXDAR_RES_19	:1;
			__RO	uint32_t	DMAFIXDAR_RES_20	:1;
			__RO	uint32_t	DMAFIXDAR_RES_21	:1;
			__RO	uint32_t	DMAFIXDAR_RES_22	:1;
			__RO	uint32_t	DMAFIXDAR_RES_23	:1;
			__RO	uint32_t	DMAFIXDAR_RES_24	:1;
			__RO	uint32_t	DMAFIXDAR_RES_25	:1;
			__RO	uint32_t	DMAFIXDAR_RES_26	:1;
			__RO	uint32_t	DMAFIXDAR_RES_27	:1;
			__RO	uint32_t	DMAFIXDAR_RES_28	:1;
			__RO	uint32_t	DMAFIXDAR_RES_29	:1;
			__RO	uint32_t	DMAFIXDAR_RES_30	:1;
			__RO	uint32_t	DMAFIXDAR_RES_31	:1;
		};
	};

	union
	{
		/* Name:	DMATCRW
		 * Offset:	0x18
		 * Size:	32 bits */
		__RW	uint32_t	DMATCRW;
		struct
		{
			__RW	uint32_t	TCRW	:24;
			__RO	uint32_t	DMATCRW_RES_24	:1;
			__RO	uint32_t	DMATCRW_RES_25	:1;
			__RO	uint32_t	DMATCRW_RES_26	:1;
			__RO	uint32_t	DMATCRW_RES_27	:1;
			__RO	uint32_t	DMATCRW_RES_28	:1;
			__RO	uint32_t	DMATCRW_RES_29	:1;
			__RO	uint32_t	DMATCRW_RES_30	:1;
			__RO	uint32_t	DMATCRW_RES_31	:1;
		};
	};

	union
	{
		/* Name:	DMACHCRB
		 * Offset:	0x1C
		 * Size:	32 bits */
		__RW	uint32_t	DMACHCRB;
		struct
		{
			__RW	uint32_t	PRI	:4;
			__RW	uint32_t	SLM	:4;
			__RW	uint32_t	DTS	:1;
			__RO	uint32_t	DMACHCRB_RES_9	:1;
			__RO	uint32_t	DMACHCRB_RES_10	:1;
			__RO	uint32_t	DMACHCRB_RES_11	:1;
			__RO	uint32_t	DMACHCRB_RES_12	:1;
			__RO	uint32_t	DMACHCRB_RES_13	:1;
			__RW	uint32_t	DREQOS_EN	:1;
			__RW	uint32_t	DRST	:1;
			__RW	uint32_t	DPTR	:8;
			__RW	uint32_t	DCNT	:8;
		};
	};

	union
	{
		/* Name:	DMASARS
		 * Offset:	0x20
		 * Size:	32 bits */
		__RW	uint32_t	DMASARS;

		/* Name:	SARS
		 * Offset:	0x20
		 * Size:	32 bits */
		__RW	uint32_t	SARS;
	};

	union
	{
		/* Name:	DMADARS
		 * Offset:	0x24
		 * Size:	32 bits */
		__RW	uint32_t	DMADARS;

		/* Name:	DARS
		 * Offset:	0x24
		 * Size:	32 bits */
		__RW	uint32_t	DARS;
	};

	union
	{
		/* Name:	DMATCRS
		 * Offset:	0x28
		 * Size:	32 bits */
		__RW	uint32_t	DMATCRS;
		struct
		{
			__RW	uint32_t	TCRS	:24;
			__RO	uint32_t	DMATCRS_RES_24	:1;
			__RO	uint32_t	DMATCRS_RES_25	:1;
			__RO	uint32_t	DMATCRS_RES_26	:1;
			__RO	uint32_t	DMATCRS_RES_27	:1;
			__RO	uint32_t	DMATCRS_RES_28	:1;
			__RO	uint32_t	DMATCRS_RES_29	:1;
			__RO	uint32_t	DMATCRS_RES_30	:1;
			__RO	uint32_t	DMATCRS_RES_31	:1;
		};
	};

	union
	{
		/* Name:	DMACHCRS
		 * Offset:	0x2C
		 * Size:	32 bits */
		__RW	uint32_t	DMACHCRS;
		struct
		{
			__RW	uint32_t	DES	:1;
			__RW	uint32_t	TES	:1;
			__RW	uint32_t	IES	:1;
			__RW	uint32_t	TSS	:2;
			__RO	uint32_t	DMACHCRS_RES_5	:1;
			__RO	uint32_t	DMACHCRS_RES_6	:1;
			__RO	uint32_t	DMACHCRS_RES_7	:1;
			__RW	uint32_t	RSS	:4;
			__RW	uint32_t	SMS	:2;
			__RW	uint32_t	DMS	:2;
			__RO	uint32_t	DMACHCRS_RES_16	:1;
			__RO	uint32_t	DMACHCRS_RES_17	:1;
			__RW	uint32_t	DSIES	:1;
			__RW	uint32_t	DSES	:1;
			__RW	uint32_t	TS2S	:2;
			__RW	uint32_t	DPBS	:1;
			__RO	uint32_t	DMACHCRS_RES_23	:1;
			__RO	uint32_t	DMACHCRS_RES_24	:1;
			__RW	uint32_t	RPTS	:3;
			__RW	uint32_t	DPMS	:2;
			__RW	uint32_t	CAIES	:1;
			__RW	uint32_t	CAES	:1;
		};
	};

	/* Name:	DMAC_CHANNEL_RES_0x30
	 * Offset:	0x30
	 * Size:	32 bits */
	__RO	uint32_t	DMAC_CHANNEL_RES_0x30;

	/* Name:	DMAC_CHANNEL_RES_0x34
	 * Offset:	0x34
	 * Size:	32 bits */
	__RO	uint32_t	DMAC_CHANNEL_RES_0x34;

	union
	{
		/* Name:	DMATCRWS
		 * Offset:	0x38
		 * Size:	32 bits */
		__RW	uint32_t	DMATCRWS;
		struct
		{
			__RW	uint32_t	TCRWS	:24;
			__RO	uint32_t	DMATCRWS_RES_24	:1;
			__RO	uint32_t	DMATCRWS_RES_25	:1;
			__RO	uint32_t	DMATCRWS_RES_26	:1;
			__RO	uint32_t	DMATCRWS_RES_27	:1;
			__RO	uint32_t	DMATCRWS_RES_28	:1;
			__RO	uint32_t	DMATCRWS_RES_29	:1;
			__RO	uint32_t	DMATCRWS_RES_30	:1;
			__RO	uint32_t	DMATCRWS_RES_31	:1;
		};
	};

	/* Name:	DMAC_CHANNEL_RES_0x3C
	 * Offset:	0x3C
	 * Size:	32 bits */
	__RO	uint32_t	DMAC_CHANNEL_RES_0x3C;

	union
	{
		/* Name:	DMARS
		 * Offset:	0x40
		 * Size:	16 bits */
		__RW	uint16_t	DMARS;
		struct
		{
			__RW	uint16_t	RID	:2;
			__RW	uint16_t	MID	:6;
			__RO	uint16_t	DMARS_RES_8	:1;
			__RO	uint16_t	DMARS_RES_9	:1;
			__RO	uint16_t	DMARS_RES_10	:1;
			__RO	uint16_t	DMARS_RES_11	:1;
			__RO	uint16_t	DMARS_RES_12	:1;
			__RO	uint16_t	DMARS_RES_13	:1;
			__RO	uint16_t	DMARS_RES_14	:1;
			__RO	uint16_t	DMARS_RES_15	:1;
		};
	};

	/* Name:	DMAC_CHANNEL_RES_0x42
	 * Offset:	0x42
	 * Size:	16 bits */
	__RO	uint16_t	DMAC_CHANNEL_RES_0x42;

	/* Name:	DMAC_CHANNEL_RES_0x44
	 * Offset:	0x44
	 * Size:	32 bits */
	__RO	uint32_t	DMAC_CHANNEL_RES_0x44;

	union
	{
		/* Name:	DMABUFCR
		 * Offset:	0x48
		 * Size:	32 bits */
		__RW	uint32_t	DMABUFCR;
		struct
		{
			__RW	uint32_t	ULB	:11;
			__RO	uint32_t	DMABUFCR_RES_11	:1;
			__RO	uint32_t	DMABUFCR_RES_12	:1;
			__RO	uint32_t	DMABUFCR_RES_13	:1;
			__RO	uint32_t	DMABUFCR_RES_14	:1;
			__RO	uint32_t	DMABUFCR_RES_15	:1;
			__RW	uint32_t	MBU	:9;
			__RO	uint32_t	DMABUFCR_RES_25	:1;
			__RO	uint32_t	DMABUFCR_RES_26	:1;
			__RO	uint32_t	DMABUFCR_RES_27	:1;
			__RO	uint32_t	DMABUFCR_RES_28	:1;
			__RO	uint32_t	DMABUFCR_RES_29	:1;
			__RO	uint32_t	DMABUFCR_RES_30	:1;
			__RO	uint32_t	DMABUFCR_RES_31	:1;
		};
	};

	/* Name:	DMAC_CHANNEL_RES_0x4C
	 * Offset:	0x4C
	 * Size:	32 bits */
	__RO	uint32_t	DMAC_CHANNEL_RES_0x4C;

	union
	{
		/* Name:	DMADPBASE
		 * Offset:	0x50
		 * Size:	32 bits */
		__RW	uint32_t	DMADPBASE;
		struct
		{
			__RW	uint32_t	SEL	:1;
			__RO	uint32_t	DMADPBASE_RES_1	:1;
			__RO	uint32_t	DMADPBASE_RES_2	:1;
			__RO	uint32_t	DMADPBASE_RES_3	:1;
			__RW	uint32_t	DPBASE	:28;
		};
	};

	union
	{
		/* Name:	DMADPCR
		 * Offset:	0x54
		 * Size:	32 bits */
		__RW	uint32_t	DMADPCR;
		struct
		{
			__RW	uint32_t	DPTR1	:4;
			__RO	uint32_t	DMADPCR_RES_4	:1;
			__RO	uint32_t	DMADPCR_RES_5	:1;
			__RO	uint32_t	DMADPCR_RES_6	:1;
			__RO	uint32_t	DMADPCR_RES_7	:1;
			__RW	uint32_t	DCNT1	:4;
			__RO	uint32_t	DMADPCR_RES_12	:1;
			__RO	uint32_t	DMADPCR_RES_13	:1;
			__RO	uint32_t	DMADPCR_RES_14	:1;
			__RO	uint32_t	DMADPCR_RES_15	:1;
			__RW	uint32_t	DIPT1	:4;
			__RO	uint32_t	DMADPCR_RES_20	:1;
			__RO	uint32_t	DMADPCR_RES_21	:1;
			__RO	uint32_t	DMADPCR_RES_22	:1;
			__RO	uint32_t	DMADPCR_RES_23	:1;
			__RW	uint32_t	DIPT	:8;
		};
	};

	union
	{
		/* Name:	DMADPEVTCR
		 * Offset:	0x58
		 * Size:	32 bits */
		__RW	uint32_t	DMADPEVTCR;
		struct
		{
			__RW	uint32_t	EVTID	:5;
			__RO	uint32_t	DMADPEVTCR_RES_5	:1;
			__RW	uint32_t	EXEN	:1;
			__RW	uint32_t	RST	:1;
			__RO	uint32_t	DMADPEVTCR_RES_8	:1;
			__RO	uint32_t	DMADPEVTCR_RES_9	:1;
			__RO	uint32_t	DMADPEVTCR_RES_10	:1;
			__RO	uint32_t	DMADPEVTCR_RES_11	:1;
			__RO	uint32_t	DMADPEVTCR_RES_12	:1;
			__RO	uint32_t	DMADPEVTCR_RES_13	:1;
			__RO	uint32_t	DMADPEVTCR_RES_14	:1;
			__RO	uint32_t	DMADPEVTCR_RES_15	:1;
			__RO	uint32_t	DMADPEVTCR_RES_16	:1;
			__RO	uint32_t	DMADPEVTCR_RES_17	:1;
			__RO	uint32_t	DMADPEVTCR_RES_18	:1;
			__RO	uint32_t	DMADPEVTCR_RES_19	:1;
			__RO	uint32_t	DMADPEVTCR_RES_20	:1;
			__RO	uint32_t	DMADPEVTCR_RES_21	:1;
			__RO	uint32_t	DMADPEVTCR_RES_22	:1;
			__RO	uint32_t	DMADPEVTCR_RES_23	:1;
			__RO	uint32_t	DMADPEVTCR_RES_24	:1;
			__RO	uint32_t	DMADPEVTCR_RES_25	:1;
			__RO	uint32_t	DMADPEVTCR_RES_26	:1;
			__RO	uint32_t	DMADPEVTCR_RES_27	:1;
			__RO	uint32_t	DMADPEVTCR_RES_28	:1;
			__RO	uint32_t	DMADPEVTCR_RES_29	:1;
			__RO	uint32_t	DMADPEVTCR_RES_30	:1;
			__RO	uint32_t	DMADPEVTCR_RES_31	:1;
		};
	};

	union
	{
		/* Name:	DMADPEVTCNT
		 * Offset:	0x5C
		 * Size:	32 bits */
		__RW	uint32_t	DMADPEVTCNT;
		struct
		{
			__RW	uint32_t	EVTCNT	:7;
			__RW	uint32_t	OV	:1;
			__RO	uint32_t	DMADPEVTCNT_RES_8	:1;
			__RO	uint32_t	DMADPEVTCNT_RES_9	:1;
			__RO	uint32_t	DMADPEVTCNT_RES_10	:1;
			__RO	uint32_t	DMADPEVTCNT_RES_11	:1;
			__RO	uint32_t	DMADPEVTCNT_RES_12	:1;
			__RO	uint32_t	DMADPEVTCNT_RES_13	:1;
			__RO	uint32_t	DMADPEVTCNT_RES_14	:1;
			__RO	uint32_t	DMADPEVTCNT_RES_15	:1;
			__RO	uint32_t	DMADPEVTCNT_RES_16	:1;
			__RO	uint32_t	DMADPEVTCNT_RES_17	:1;
			__RO	uint32_t	DMADPEVTCNT_RES_18	:1;
			__RO	uint32_t	DMADPEVTCNT_RES_19	:1;
			__RO	uint32_t	DMADPEVTCNT_RES_20	:1;
			__RO	uint32_t	DMADPEVTCNT_RES_21	:1;
			__RO	uint32_t	DMADPEVTCNT_RES_22	:1;
			__RO	uint32_t	DMADPEVTCNT_RES_23	:1;
			__RO	uint32_t	DMADPEVTCNT_RES_24	:1;
			__RO	uint32_t	DMADPEVTCNT_RES_25	:1;
			__RO	uint32_t	DMADPEVTCNT_RES_26	:1;
			__RO	uint32_t	DMADPEVTCNT_RES_27	:1;
			__RO	uint32_t	DMADPEVTCNT_RES_28	:1;
			__RO	uint32_t	DMADPEVTCNT_RES_29	:1;
			__RO	uint32_t	DMADPEVTCNT_RES_30	:1;
			__RO	uint32_t	DMADPEVTCNT_RES_31	:1;
		};
	};

	union
	{
		/* Name:	DMAFIXDPBASE
		 * Offset:	0x60
		 * Size:	32 bits */
		__RW	uint32_t	DMAFIXDPBASE;
		struct
		{
			__RW	uint32_t	FIXDPBASE	:8;
			__RO	uint32_t	DMAFIXDPBASE_RES_8	:1;
			__RO	uint32_t	DMAFIXDPBASE_RES_9	:1;
			__RO	uint32_t	DMAFIXDPBASE_RES_10	:1;
			__RO	uint32_t	DMAFIXDPBASE_RES_11	:1;
			__RO	uint32_t	DMAFIXDPBASE_RES_12	:1;
			__RO	uint32_t	DMAFIXDPBASE_RES_13	:1;
			__RO	uint32_t	DMAFIXDPBASE_RES_14	:1;
			__RO	uint32_t	DMAFIXDPBASE_RES_15	:1;
			__RO	uint32_t	DMAFIXDPBASE_RES_16	:1;
			__RO	uint32_t	DMAFIXDPBASE_RES_17	:1;
			__RO	uint32_t	DMAFIXDPBASE_RES_18	:1;
			__RO	uint32_t	DMAFIXDPBASE_RES_19	:1;
			__RO	uint32_t	DMAFIXDPBASE_RES_20	:1;
			__RO	uint32_t	DMAFIXDPBASE_RES_21	:1;
			__RO	uint32_t	DMAFIXDPBASE_RES_22	:1;
			__RO	uint32_t	DMAFIXDPBASE_RES_23	:1;
			__RO	uint32_t	DMAFIXDPBASE_RES_24	:1;
			__RO	uint32_t	DMAFIXDPBASE_RES_25	:1;
			__RO	uint32_t	DMAFIXDPBASE_RES_26	:1;
			__RO	uint32_t	DMAFIXDPBASE_RES_27	:1;
			__RO	uint32_t	DMAFIXDPBASE_RES_28	:1;
			__RO	uint32_t	DMAFIXDPBASE_RES_29	:1;
			__RO	uint32_t	DMAFIXDPBASE_RES_30	:1;
			__RO	uint32_t	DMAFIXDPBASE_RES_31	:1;
		};
	};

	/* Name:	DMAC_CHANNEL_RES_0x64
	 * Offset:	0x64
	 * Size:	32 bits */
	__RO	uint32_t	DMAC_CHANNEL_RES_0x64;

	union
	{
		/* Name:	DMAMMUSAR
		 * Offset:	0x68
		 * Size:	32 bits */
		__RW	uint32_t	DMAMMUSAR;

		/* Name:	MMUSAR
		 * Offset:	0x68
		 * Size:	32 bits */
		__RW	uint32_t	MMUSAR;
	};

	union
	{
		/* Name:	DMAMMUDAR
		 * Offset:	0x6C
		 * Size:	32 bits */
		__RW	uint32_t	DMAMMUDAR;

		/* Name:	MMUDAR
		 * Offset:	0x6C
		 * Size:	32 bits */
		__RW	uint32_t	MMUDAR;
	};

	union
	{
		/* Name:	DMAERR
		 * Offset:	0x70
		 * Size:	32 bits */
		__RW	uint32_t	DMAERR;

		/* Name:	ERR
		 * Offset:	0x70
		 * Size:	32 bits */
		__RW	uint32_t	ERR;
	};

	union
	{
		/* Name:	DMACACHE
		 * Offset:	0x74
		 * Size:	32 bits */
		__RW	uint32_t	DMACACHE;

		/* Name:	CACHE
		 * Offset:	0x74
		 * Size:	32 bits */
		__RW	uint32_t	CACHE;
	};

	union
	{
		/* Name:	DMAREGIONID
		 * Offset:	0x78
		 * Size:	32 bits */
		__RW	uint32_t	DMAREGIONID;
		struct
		{
			__RW	uint32_t	REGIONID	:4;
			__RO	uint32_t	DMAREGIONID_RES_4	:1;
			__RO	uint32_t	DMAREGIONID_RES_5	:1;
			__RO	uint32_t	DMAREGIONID_RES_6	:1;
			__RO	uint32_t	DMAREGIONID_RES_7	:1;
			__RO	uint32_t	DMAREGIONID_RES_8	:1;
			__RO	uint32_t	DMAREGIONID_RES_9	:1;
			__RO	uint32_t	DMAREGIONID_RES_10	:1;
			__RO	uint32_t	DMAREGIONID_RES_11	:1;
			__RO	uint32_t	DMAREGIONID_RES_12	:1;
			__RO	uint32_t	DMAREGIONID_RES_13	:1;
			__RO	uint32_t	DMAREGIONID_RES_14	:1;
			__RO	uint32_t	DMAREGIONID_RES_15	:1;
			__RO	uint32_t	DMAREGIONID_RES_16	:1;
			__RO	uint32_t	DMAREGIONID_RES_17	:1;
			__RO	uint32_t	DMAREGIONID_RES_18	:1;
			__RO	uint32_t	DMAREGIONID_RES_19	:1;
			__RO	uint32_t	DMAREGIONID_RES_20	:1;
			__RO	uint32_t	DMAREGIONID_RES_21	:1;
			__RO	uint32_t	DMAREGIONID_RES_22	:1;
			__RO	uint32_t	DMAREGIONID_RES_23	:1;
			__RO	uint32_t	DMAREGIONID_RES_24	:1;
			__RO	uint32_t	DMAREGIONID_RES_25	:1;
			__RO	uint32_t	DMAREGIONID_RES_26	:1;
			__RO	uint32_t	DMAREGIONID_RES_27	:1;
			__RO	uint32_t	DMAREGIONID_RES_28	:1;
			__RO	uint32_t	DMAREGIONID_RES_29	:1;
			__RO	uint32_t	DMAREGIONID_RES_30	:1;
			__RO	uint32_t	DMAREGIONID_RES_31	:1;
		};
	};

	union
	{
		/* Name:	DMADEBUG
		 * Offset:	0x7C
		 * Size:	32 bits */
		__RW	uint32_t	DMADEBUG;
	};

	union
	{
		/* Name:	DMACHID
		 * Offset:	0x80
		 * Size:	32 bits */
		__RW	uint32_t	DMACHID;
		struct
		{
			__RW	uint32_t	CH_ID	:4;
			__RO	uint32_t	DMACHID_RES_4	:1;
			__RO	uint32_t	DMACHID_RES_5	:1;
			__RO	uint32_t	DMACHID_RES_6	:1;
			__RO	uint32_t	DMACHID_RES_7	:1;
			__RO	uint32_t	DMACHID_RES_8	:1;
			__RO	uint32_t	DMACHID_RES_9	:1;
			__RO	uint32_t	DMACHID_RES_10	:1;
			__RO	uint32_t	DMACHID_RES_11	:1;
			__RO	uint32_t	DMACHID_RES_12	:1;
			__RO	uint32_t	DMACHID_RES_13	:1;
			__RO	uint32_t	DMACHID_RES_14	:1;
			__RO	uint32_t	DMACHID_RES_15	:1;
			__RO	uint32_t	DMACHID_RES_16	:1;
			__RO	uint32_t	DMACHID_RES_17	:1;
			__RO	uint32_t	DMACHID_RES_18	:1;
			__RO	uint32_t	DMACHID_RES_19	:1;
			__RO	uint32_t	DMACHID_RES_20	:1;
			__RO	uint32_t	DMACHID_RES_21	:1;
			__RO	uint32_t	DMACHID_RES_22	:1;
			__RO	uint32_t	DMACHID_RES_23	:1;
			__RO	uint32_t	DMACHID_RES_24	:1;
			__RO	uint32_t	DMACHID_RES_25	:1;
			__RO	uint32_t	DMACHID_RES_26	:1;
			__RO	uint32_t	DMACHID_RES_27	:1;
			__RO	uint32_t	DMACHID_RES_28	:1;
			__RO	uint32_t	DMACHID_RES_29	:1;
			__RO	uint32_t	DMACHID_RES_30	:1;
			__RO	uint32_t	DMACHID_RES_31	:1;
		};
	};

	/* Name:	DMAC_CHANNEL_RES_0x84
	 * Offset:	0x84
	 * Size:	32 bits */
	__RO	uint32_t	DMAC_CHANNEL_RES_0x84;

	/* Name:	DMAC_CHANNEL_RES_0x88
	 * Offset:	0x88
	 * Size:	32 bits */
	__RO	uint32_t	DMAC_CHANNEL_RES_0x88;

	/* Name:	DMAC_CHANNEL_RES_0x8C
	 * Offset:	0x8C
	 * Size:	32 bits */
	__RO	uint32_t	DMAC_CHANNEL_RES_0x8C;

	/* Name:	DMAC_CHANNEL_RES_0x90
	 * Offset:	0x90
	 * Size:	32 bits */
	__RO	uint32_t	DMAC_CHANNEL_RES_0x90;

	/* Name:	DMAC_CHANNEL_RES_0x94
	 * Offset:	0x94
	 * Size:	32 bits */
	__RO	uint32_t	DMAC_CHANNEL_RES_0x94;

	/* Name:	DMAC_CHANNEL_RES_0x98
	 * Offset:	0x98
	 * Size:	32 bits */
	__RO	uint32_t	DMAC_CHANNEL_RES_0x98;

	/* Name:	DMAC_CHANNEL_RES_0x9C
	 * Offset:	0x9C
	 * Size:	32 bits */
	__RO	uint32_t	DMAC_CHANNEL_RES_0x9C;

	/* Name:	DMAC_CHANNEL_RES_0xA0
	 * Offset:	0xA0
	 * Size:	32 bits */
	__RO	uint32_t	DMAC_CHANNEL_RES_0xA0;

	/* Name:	DMAC_CHANNEL_RES_0xA4
	 * Offset:	0xA4
	 * Size:	32 bits */
	__RO	uint32_t	DMAC_CHANNEL_RES_0xA4;

	/* Name:	DMAC_CHANNEL_RES_0xA8
	 * Offset:	0xA8
	 * Size:	32 bits */
	__RO	uint32_t	DMAC_CHANNEL_RES_0xA8;

	/* Name:	DMAC_CHANNEL_RES_0xAC
	 * Offset:	0xAC
	 * Size:	32 bits */
	__RO	uint32_t	DMAC_CHANNEL_RES_0xAC;

	union
	{
		/* Name:	DMASEC
		 * Offset:	0xB0
		 * Size:	32 bits */
		__RW	uint32_t	DMASEC;
		struct
		{
			__RW	uint32_t	S	:1;
			__RO	uint32_t	DMASEC_RES_1	:1;
			__RO	uint32_t	DMASEC_RES_2	:1;
			__RO	uint32_t	DMASEC_RES_3	:1;
			__RO	uint32_t	DMASEC_RES_4	:1;
			__RO	uint32_t	DMASEC_RES_5	:1;
			__RO	uint32_t	DMASEC_RES_6	:1;
			__RO	uint32_t	DMASEC_RES_7	:1;
			__RO	uint32_t	DMASEC_RES_8	:1;
			__RO	uint32_t	DMASEC_RES_9	:1;
			__RO	uint32_t	DMASEC_RES_10	:1;
			__RO	uint32_t	DMASEC_RES_11	:1;
			__RO	uint32_t	DMASEC_RES_12	:1;
			__RO	uint32_t	DMASEC_RES_13	:1;
			__RO	uint32_t	DMASEC_RES_14	:1;
			__RO	uint32_t	DMASEC_RES_15	:1;
			__RO	uint32_t	DMASEC_RES_16	:1;
			__RO	uint32_t	DMASEC_RES_17	:1;
			__RO	uint32_t	DMASEC_RES_18	:1;
			__RO	uint32_t	DMASEC_RES_19	:1;
			__RO	uint32_t	DMASEC_RES_20	:1;
			__RO	uint32_t	DMASEC_RES_21	:1;
			__RO	uint32_t	DMASEC_RES_22	:1;
			__RO	uint32_t	DMASEC_RES_23	:1;
			__RO	uint32_t	DMASEC_RES_24	:1;
			__RO	uint32_t	DMASEC_RES_25	:1;
			__RO	uint32_t	DMASEC_RES_26	:1;
			__RO	uint32_t	DMASEC_RES_27	:1;
			__RO	uint32_t	DMASEC_RES_28	:1;
			__RO	uint32_t	DMASEC_RES_29	:1;
			__RO	uint32_t	DMASEC_RES_30	:1;
			__RO	uint32_t	DMASEC_RES_31	:1;
		};
	};

	/* Name:	DMAC_CHANNEL_RES_0xB4
	 * Offset:	0xB4
	 * Size:	32 bits */
	__RO	uint32_t	DMAC_CHANNEL_RES_0xB4;

	/* Name:	DMAC_CHANNEL_RES_0xB8
	 * Offset:	0xB8
	 * Size:	32 bits */
	__RO	uint32_t	DMAC_CHANNEL_RES_0xB8;

	/* Name:	DMAC_CHANNEL_RES_0xBC
	 * Offset:	0xBC
	 * Size:	32 bits */
	__RO	uint32_t	DMAC_CHANNEL_RES_0xBC;

	/* Name:	DMAC_CHANNEL_RES_0xC0
	 * Offset:	0xC0
	 * Size:	32 bits */
	__RO	uint32_t	DMAC_CHANNEL_RES_0xC0;

	/* Name:	DMAC_CHANNEL_RES_0xC4
	 * Offset:	0xC4
	 * Size:	32 bits */
	__RO	uint32_t	DMAC_CHANNEL_RES_0xC4;

	/* Name:	DMAC_CHANNEL_RES_0xC8
	 * Offset:	0xC8
	 * Size:	32 bits */
	__RO	uint32_t	DMAC_CHANNEL_RES_0xC8;

	/* Name:	DMAC_CHANNEL_RES_0xCC
	 * Offset:	0xCC
	 * Size:	32 bits */
	__RO	uint32_t	DMAC_CHANNEL_RES_0xCC;

	/* Name:	DMAC_CHANNEL_RES_0xD0
	 * Offset:	0xD0
	 * Size:	32 bits */
	__RO	uint32_t	DMAC_CHANNEL_RES_0xD0;

	/* Name:	DMAC_CHANNEL_RES_0xD4
	 * Offset:	0xD4
	 * Size:	32 bits */
	__RO	uint32_t	DMAC_CHANNEL_RES_0xD4;

	/* Name:	DMAC_CHANNEL_RES_0xD8
	 * Offset:	0xD8
	 * Size:	32 bits */
	__RO	uint32_t	DMAC_CHANNEL_RES_0xD8;

	/* Name:	DMAC_CHANNEL_RES_0xDC
	 * Offset:	0xDC
	 * Size:	32 bits */
	__RO	uint32_t	DMAC_CHANNEL_RES_0xDC;

	/* Name:	DMAC_CHANNEL_RES_0xE0
	 * Offset:	0xE0
	 * Size:	32 bits */
	__RO	uint32_t	DMAC_CHANNEL_RES_0xE0;

	/* Name:	DMAC_CHANNEL_RES_0xE4
	 * Offset:	0xE4
	 * Size:	32 bits */
	__RO	uint32_t	DMAC_CHANNEL_RES_0xE4;

	/* Name:	DMAC_CHANNEL_RES_0xE8
	 * Offset:	0xE8
	 * Size:	32 bits */
	__RO	uint32_t	DMAC_CHANNEL_RES_0xE8;

	/* Name:	DMAC_CHANNEL_RES_0xEC
	 * Offset:	0xEC
	 * Size:	32 bits */
	__RO	uint32_t	DMAC_CHANNEL_RES_0xEC;

	/* Name:	DMAC_CHANNEL_RES_0xF0
	 * Offset:	0xF0
	 * Size:	32 bits */
	__RO	uint32_t	DMAC_CHANNEL_RES_0xF0;

	/* Name:	DMAC_CHANNEL_RES_0xF4
	 * Offset:	0xF4
	 * Size:	32 bits */
	__RO	uint32_t	DMAC_CHANNEL_RES_0xF4;

	/* Name:	DMAC_CHANNEL_RES_0xF8
	 * Offset:	0xF8
	 * Size:	32 bits */
	__RO	uint32_t	DMAC_CHANNEL_RES_0xF8;

	/* Name:	DMAC_CHANNEL_RES_0xFC
	 * Offset:	0xFC
	 * Size:	32 bits */
	__RO	uint32_t	DMAC_CHANNEL_RES_0xFC;

	union
	{
		/* Name:	DMACHCLR
		 * Offset:	0x100
		 * Size:	32 bits */
		__RW	uint32_t	DMACHCLR;
		struct
		{
			__RW	uint32_t	CLR	:1;
			__RO	uint32_t	DMACHCLR_RES_1	:1;
			__RO	uint32_t	DMACHCLR_RES_2	:1;
			__RO	uint32_t	DMACHCLR_RES_3	:1;
			__RO	uint32_t	DMACHCLR_RES_4	:1;
			__RO	uint32_t	DMACHCLR_RES_5	:1;
			__RO	uint32_t	DMACHCLR_RES_6	:1;
			__RO	uint32_t	DMACHCLR_RES_7	:1;
			__RO	uint32_t	DMACHCLR_RES_8	:1;
			__RO	uint32_t	DMACHCLR_RES_9	:1;
			__RO	uint32_t	DMACHCLR_RES_10	:1;
			__RO	uint32_t	DMACHCLR_RES_11	:1;
			__RO	uint32_t	DMACHCLR_RES_12	:1;
			__RO	uint32_t	DMACHCLR_RES_13	:1;
			__RO	uint32_t	DMACHCLR_RES_14	:1;
			__RO	uint32_t	DMACHCLR_RES_15	:1;
			__RO	uint32_t	DMACHCLR_RES_16	:1;
			__RO	uint32_t	DMACHCLR_RES_17	:1;
			__RO	uint32_t	DMACHCLR_RES_18	:1;
			__RO	uint32_t	DMACHCLR_RES_19	:1;
			__RO	uint32_t	DMACHCLR_RES_20	:1;
			__RO	uint32_t	DMACHCLR_RES_21	:1;
			__RO	uint32_t	DMACHCLR_RES_22	:1;
			__RO	uint32_t	DMACHCLR_RES_23	:1;
			__RO	uint32_t	DMACHCLR_RES_24	:1;
			__RO	uint32_t	DMACHCLR_RES_25	:1;
			__RO	uint32_t	DMACHCLR_RES_26	:1;
			__RO	uint32_t	DMACHCLR_RES_27	:1;
			__RO	uint32_t	DMACHCLR_RES_28	:1;
			__RO	uint32_t	DMACHCLR_RES_29	:1;
			__RO	uint32_t	DMACHCLR_RES_30	:1;
			__RO	uint32_t	DMACHCLR_RES_31	:1;
		};
	};

} DMAC_Channel_t;

/******************************************************************************
 *	Name	Offset	Size	R/W
 ******************************************************************************
 *	DPSAR	0x0		32		RW
 *	DPDAR	0x4		32		RW
 *	DPTCR	0x8		32		RW
 *	DPCHCR	0xC		32		RW
******************************************************************************/
typedef struct
{
	union
	{
		/* Name:	DPSAR
		 * Offset:	0x0
		 * Size:	32 bits */
		__RW	uint32_t	DPSAR;

		/* Name:	SAR
		 * Offset:	0x0
		 * Size:	32 bits */
		__RW	uint32_t	SAR;
	};

	union
	{
		/* Name:	DPDAR
		 * Offset:	0x4
		 * Size:	32 bits */
		__RW	uint32_t	DPDAR;

		/* Name:	DAR
		 * Offset:	0x4
		 * Size:	32 bits */
		__RW	uint32_t	DAR;
	};

	union
	{
		/* Name:	DPTCR
		 * Offset:	0x8
		 * Size:	32 bits */
		__RW	uint32_t	DPTCR;
		struct
		{
			__RW	uint32_t	TCR	:24;
			__RO	uint32_t	DPTCR_RES_24	:1;
			__RO	uint32_t	DPTCR_RES_25	:1;
			__RO	uint32_t	DPTCR_RES_26	:1;
			__RO	uint32_t	DPTCR_RES_27	:1;
			__RO	uint32_t	DPTCR_RES_28	:1;
			__RO	uint32_t	DPTCR_RES_29	:1;
			__RO	uint32_t	DPTCR_RES_30	:1;
			__RO	uint32_t	DPTCR_RES_31	:1;
		};
	};

	union
	{
		/* Name:	DPCHCR
		 * Offset:	0xC
		 * Size:	32 bits */
		__RW	uint32_t	DPCHCR;
		struct
		{
			__RW	uint32_t	TS	:4;
			__RW	uint32_t	DSIE	:1;
			__RW	uint32_t	WAIT	:1;
			__RW	uint32_t	RS	:2;
			__RW	uint32_t	SM	:2;
			__RW	uint32_t	DM	:2;
			__RW	uint32_t	INT	:1;
			__RW	uint32_t	INV	:1;
			__RW	uint32_t	DRQMD	:2;
			__RW	uint32_t	DRS	:8;
			__RW	uint32_t	DRSEL	:2;
			__RW	uint32_t	DS	:1;
			__RW	uint32_t	DL	:1;
			__RW	uint32_t	AL	:1;
			__RW	uint32_t	AM	:1;
			__RW	uint32_t	DO	:1;
			__RW	uint32_t	DA	:1;
		};
	};

} DMAC_Descriptor_t;

/******************************************************************************
 *	Name		Offset	Size	R/W
 ******************************************************************************
 *	DMADMICR	0x10	32		RW
 *	DMADMISTA	0x20	32		RW
 *	DMAPRISYNC	0x40	32		RW
 *	DMADMAOR	0x60	32		RW
 *	DMADBGOR	0x70	32		RW
 *	DMADPSEC	0xA0	32		RW
 *	DMAFLUSH	0xB0	32		RW
 *	DMAERR_DET	0xC0	32		RW
 *	DMAERR_ADR	0xC4	32		RW
 *	DMAERR_PID	0xC8	32		RW
 *	DMAADRFB	0xCC	32		RW
 *	DMADMCMP_STATUS	0xF0	32		RW
 *	DMARATE_RD	0xF4	32		RW
 *	DMARATE_WR	0xF8	32		RW
 *	DMADPRAMEDC	0xFC	32		RW
 *	DMADESMEM	0x800	32		RW
******************************************************************************/
typedef struct
{
	/* Name:	DMA_COMMON_RES_0x0
	 * Offset:	0x0
	 * Size:	32 bits */
	__RO	uint32_t	DMA_COMMON_RES_0x0;

	/* Name:	DMA_COMMON_RES_0x4
	 * Offset:	0x4
	 * Size:	32 bits */
	__RO	uint32_t	DMA_COMMON_RES_0x4;

	/* Name:	DMA_COMMON_RES_0x8
	 * Offset:	0x8
	 * Size:	32 bits */
	__RO	uint32_t	DMA_COMMON_RES_0x8;

	/* Name:	DMA_COMMON_RES_0xC
	 * Offset:	0xC
	 * Size:	32 bits */
	__RO	uint32_t	DMA_COMMON_RES_0xC;

	union
	{
		/* Name:	DMADMICR
		 * Offset:	0x10
		 * Size:	32 bits */
		__RW	uint32_t	DMADMICR;

		/* Name:	DMICR
		 * Offset:	0x10
		 * Size:	32 bits */
		__RW	uint32_t	DMICR;
	};

	/* Name:	DMA_COMMON_RES_0x14
	 * Offset:	0x14
	 * Size:	32 bits */
	__RO	uint32_t	DMA_COMMON_RES_0x14;

	/* Name:	DMA_COMMON_RES_0x18
	 * Offset:	0x18
	 * Size:	32 bits */
	__RO	uint32_t	DMA_COMMON_RES_0x18;

	/* Name:	DMA_COMMON_RES_0x1C
	 * Offset:	0x1C
	 * Size:	32 bits */
	__RO	uint32_t	DMA_COMMON_RES_0x1C;

	union
	{
		/* Name:	DMADMISTA
		 * Offset:	0x20
		 * Size:	32 bits */
		__RW	uint32_t	DMADMISTA;

		/* Name:	DMISTA
		 * Offset:	0x20
		 * Size:	32 bits */
		__RW	uint32_t	DMISTA;
	};

	/* Name:	DMA_COMMON_RES_0x24
	 * Offset:	0x24
	 * Size:	32 bits */
	__RO	uint32_t	DMA_COMMON_RES_0x24;

	/* Name:	DMA_COMMON_RES_0x28
	 * Offset:	0x28
	 * Size:	32 bits */
	__RO	uint32_t	DMA_COMMON_RES_0x28;

	/* Name:	DMA_COMMON_RES_0x2C
	 * Offset:	0x2C
	 * Size:	32 bits */
	__RO	uint32_t	DMA_COMMON_RES_0x2C;

	/* Name:	DMA_COMMON_RES_0x30
	 * Offset:	0x30
	 * Size:	32 bits */
	__RO	uint32_t	DMA_COMMON_RES_0x30;

	/* Name:	DMA_COMMON_RES_0x34
	 * Offset:	0x34
	 * Size:	32 bits */
	__RO	uint32_t	DMA_COMMON_RES_0x34;

	/* Name:	DMA_COMMON_RES_0x38
	 * Offset:	0x38
	 * Size:	32 bits */
	__RO	uint32_t	DMA_COMMON_RES_0x38;

	/* Name:	DMA_COMMON_RES_0x3C
	 * Offset:	0x3C
	 * Size:	32 bits */
	__RO	uint32_t	DMA_COMMON_RES_0x3C;

	union
	{
		/* Name:	DMAPRISYNC
		 * Offset:	0x40
		 * Size:	32 bits */
		__RW	uint32_t	DMAPRISYNC;

		/* Name:	PRISYNC
		 * Offset:	0x40
		 * Size:	32 bits */
		__RW	uint32_t	PRISYNC;
	};

	/* Name:	DMA_COMMON_RES_0x44
	 * Offset:	0x44
	 * Size:	32 bits */
	__RO	uint32_t	DMA_COMMON_RES_0x44;

	/* Name:	DMA_COMMON_RES_0x48
	 * Offset:	0x48
	 * Size:	32 bits */
	__RO	uint32_t	DMA_COMMON_RES_0x48;

	/* Name:	DMA_COMMON_RES_0x4C
	 * Offset:	0x4C
	 * Size:	32 bits */
	__RO	uint32_t	DMA_COMMON_RES_0x4C;

	/* Name:	DMA_COMMON_RES_0x50
	 * Offset:	0x50
	 * Size:	32 bits */
	__RO	uint32_t	DMA_COMMON_RES_0x50;

	/* Name:	DMA_COMMON_RES_0x54
	 * Offset:	0x54
	 * Size:	32 bits */
	__RO	uint32_t	DMA_COMMON_RES_0x54;

	/* Name:	DMA_COMMON_RES_0x58
	 * Offset:	0x58
	 * Size:	32 bits */
	__RO	uint32_t	DMA_COMMON_RES_0x58;

	/* Name:	DMA_COMMON_RES_0x5C
	 * Offset:	0x5C
	 * Size:	32 bits */
	__RO	uint32_t	DMA_COMMON_RES_0x5C;

	union
	{
		/* Name:	DMADMAOR
		 * Offset:	0x60
		 * Size:	32 bits */
		__RW	uint32_t	DMADMAOR;

		/* Name:	DMAOR
		 * Offset:	0x60
		 * Size:	32 bits */
		__RW	uint32_t	DMAOR;
	};

	/* Name:	DMA_COMMON_RES_0x64
	 * Offset:	0x64
	 * Size:	32 bits */
	__RO	uint32_t	DMA_COMMON_RES_0x64;

	/* Name:	DMA_COMMON_RES_0x68
	 * Offset:	0x68
	 * Size:	32 bits */
	__RO	uint32_t	DMA_COMMON_RES_0x68;

	/* Name:	DMA_COMMON_RES_0x6C
	 * Offset:	0x6C
	 * Size:	32 bits */
	__RO	uint32_t	DMA_COMMON_RES_0x6C;

	union
	{
		/* Name:	DMADBGOR
		 * Offset:	0x70
		 * Size:	32 bits */
		__RW	uint32_t	DMADBGOR;

		/* Name:	DBGOR
		 * Offset:	0x70
		 * Size:	32 bits */
		__RW	uint32_t	DBGOR;
	};

	/* Name:	DMA_COMMON_RES_0x74
	 * Offset:	0x74
	 * Size:	32 bits */
	__RO	uint32_t	DMA_COMMON_RES_0x74;

	/* Name:	DMA_COMMON_RES_0x78
	 * Offset:	0x78
	 * Size:	32 bits */
	__RO	uint32_t	DMA_COMMON_RES_0x78;

	/* Name:	DMA_COMMON_RES_0x7C
	 * Offset:	0x7C
	 * Size:	32 bits */
	__RO	uint32_t	DMA_COMMON_RES_0x7C;

	/* Name:	DMA_COMMON_RES_0x80
	 * Offset:	0x80
	 * Size:	32 bits */
	__RO	uint32_t	DMA_COMMON_RES_0x80;

	/* Name:	DMA_COMMON_RES_0x84
	 * Offset:	0x84
	 * Size:	32 bits */
	__RO	uint32_t	DMA_COMMON_RES_0x84;

	/* Name:	DMA_COMMON_RES_0x88
	 * Offset:	0x88
	 * Size:	32 bits */
	__RO	uint32_t	DMA_COMMON_RES_0x88;

	/* Name:	DMA_COMMON_RES_0x8C
	 * Offset:	0x8C
	 * Size:	32 bits */
	__RO	uint32_t	DMA_COMMON_RES_0x8C;

	/* Name:	DMA_COMMON_RES_0x90
	 * Offset:	0x90
	 * Size:	32 bits */
	__RO	uint32_t	DMA_COMMON_RES_0x90;

	/* Name:	DMA_COMMON_RES_0x94
	 * Offset:	0x94
	 * Size:	32 bits */
	__RO	uint32_t	DMA_COMMON_RES_0x94;

	/* Name:	DMA_COMMON_RES_0x98
	 * Offset:	0x98
	 * Size:	32 bits */
	__RO	uint32_t	DMA_COMMON_RES_0x98;

	/* Name:	DMA_COMMON_RES_0x9C
	 * Offset:	0x9C
	 * Size:	32 bits */
	__RO	uint32_t	DMA_COMMON_RES_0x9C;

	union
	{
		/* Name:	DMADPSEC
		 * Offset:	0xA0
		 * Size:	32 bits */
		__RW	uint32_t	DMADPSEC;

		/* Name:	DPSEC
		 * Offset:	0xA0
		 * Size:	32 bits */
		__RW	uint32_t	DPSEC;
	};

	/* Name:	DMA_COMMON_RES_0xA4
	 * Offset:	0xA4
	 * Size:	32 bits */
	__RO	uint32_t	DMA_COMMON_RES_0xA4;

	/* Name:	DMA_COMMON_RES_0xA8
	 * Offset:	0xA8
	 * Size:	32 bits */
	__RO	uint32_t	DMA_COMMON_RES_0xA8;

	/* Name:	DMA_COMMON_RES_0xAC
	 * Offset:	0xAC
	 * Size:	32 bits */
	__RO	uint32_t	DMA_COMMON_RES_0xAC;

	union
	{
		/* Name:	DMAFLUSH
		 * Offset:	0xB0
		 * Size:	32 bits */
		__RW	uint32_t	DMAFLUSH;

		/* Name:	FLUSH
		 * Offset:	0xB0
		 * Size:	32 bits */
		__RW	uint32_t	FLUSH;
	};

	/* Name:	DMA_COMMON_RES_0xB4
	 * Offset:	0xB4
	 * Size:	32 bits */
	__RO	uint32_t	DMA_COMMON_RES_0xB4;

	/* Name:	DMA_COMMON_RES_0xB8
	 * Offset:	0xB8
	 * Size:	32 bits */
	__RO	uint32_t	DMA_COMMON_RES_0xB8;

	/* Name:	DMA_COMMON_RES_0xBC
	 * Offset:	0xBC
	 * Size:	32 bits */
	__RO	uint32_t	DMA_COMMON_RES_0xBC;

	union
	{
		/* Name:	DMAERR_DET
		 * Offset:	0xC0
		 * Size:	32 bits */
		__RW	uint32_t	DMAERR_DET;

		/* Name:	ERR_DET
		 * Offset:	0xC0
		 * Size:	32 bits */
		__RW	uint32_t	ERR_DET;
	};

	union
	{
		/* Name:	DMAERR_ADR
		 * Offset:	0xC4
		 * Size:	32 bits */
		__RW	uint32_t	DMAERR_ADR;

		/* Name:	ERR_ADR
		 * Offset:	0xC4
		 * Size:	32 bits */
		__RW	uint32_t	ERR_ADR;
	};

	union
	{
		/* Name:	DMAERR_PID
		 * Offset:	0xC8
		 * Size:	32 bits */
		__RW	uint32_t	DMAERR_PID;

		/* Name:	ERR_PID
		 * Offset:	0xC8
		 * Size:	32 bits */
		__RW	uint32_t	ERR_PID;
	};

	union
	{
		/* Name:	DMAADRFB
		 * Offset:	0xCC
		 * Size:	32 bits */
		__RW	uint32_t	DMAADRFB;
		struct
		{
			__RW	uint32_t	P_ADDRFB_ERR	:1;
			__RO	uint32_t	DMAADRFB_RES_1	:1;
			__RO	uint32_t	DMAADRFB_RES_2	:1;
			__RO	uint32_t	DMAADRFB_RES_3	:1;
			__RO	uint32_t	DMAADRFB_RES_4	:1;
			__RO	uint32_t	DMAADRFB_RES_5	:1;
			__RO	uint32_t	DMAADRFB_RES_6	:1;
			__RO	uint32_t	DMAADRFB_RES_7	:1;
			__RO	uint32_t	DMAADRFB_RES_8	:1;
			__RO	uint32_t	DMAADRFB_RES_9	:1;
			__RO	uint32_t	DMAADRFB_RES_10	:1;
			__RO	uint32_t	DMAADRFB_RES_11	:1;
			__RO	uint32_t	DMAADRFB_RES_12	:1;
			__RO	uint32_t	DMAADRFB_RES_13	:1;
			__RO	uint32_t	DMAADRFB_RES_14	:1;
			__RO	uint32_t	DMAADRFB_RES_15	:1;
			__RW	uint32_t	REF_A	:9;
			__RO	uint32_t	DMAADRFB_RES_25	:1;
			__RO	uint32_t	DMAADRFB_RES_26	:1;
			__RO	uint32_t	DMAADRFB_RES_27	:1;
			__RO	uint32_t	DMAADRFB_RES_28	:1;
			__RO	uint32_t	DMAADRFB_RES_29	:1;
			__RO	uint32_t	DMAADRFB_RES_30	:1;
			__RW	uint32_t	ADDRFB_ENABLE	:1;
		};
	};

	/* Name:	DMA_COMMON_RES_0xD0
	 * Offset:	0xD0
	 * Size:	32 bits */
	__RO	uint32_t	DMA_COMMON_RES_0xD0;

	/* Name:	DMA_COMMON_RES_0xD4
	 * Offset:	0xD4
	 * Size:	32 bits */
	__RO	uint32_t	DMA_COMMON_RES_0xD4;

	/* Name:	DMA_COMMON_RES_0xD8
	 * Offset:	0xD8
	 * Size:	32 bits */
	__RO	uint32_t	DMA_COMMON_RES_0xD8;

	/* Name:	DMA_COMMON_RES_0xDC
	 * Offset:	0xDC
	 * Size:	32 bits */
	__RO	uint32_t	DMA_COMMON_RES_0xDC;

	/* Name:	DMA_COMMON_RES_0xE0
	 * Offset:	0xE0
	 * Size:	32 bits */
	__RO	uint32_t	DMA_COMMON_RES_0xE0;

	/* Name:	DMA_COMMON_RES_0xE4
	 * Offset:	0xE4
	 * Size:	32 bits */
	__RO	uint32_t	DMA_COMMON_RES_0xE4;

	/* Name:	DMA_COMMON_RES_0xE8
	 * Offset:	0xE8
	 * Size:	32 bits */
	__RO	uint32_t	DMA_COMMON_RES_0xE8;

	/* Name:	DMA_COMMON_RES_0xEC
	 * Offset:	0xEC
	 * Size:	32 bits */
	__RO	uint32_t	DMA_COMMON_RES_0xEC;

	union
	{
		/* Name:	DMADMCMP_STATUS
		 * Offset:	0xF0
		 * Size:	32 bits */
		__RW	uint32_t	DMADMCMP_STATUS;

		/* Name:	DMCMP_STATUS
		 * Offset:	0xF0
		 * Size:	32 bits */
		__RW	uint32_t	DMCMP_STATUS;
	};

	union
	{
		/* Name:	DMARATE_RD
		 * Offset:	0xF4
		 * Size:	32 bits */
		__RW	uint32_t	DMARATE_RD;
		struct
		{
			__RW	uint32_t	RATE_RD_ACCESS_CNT	:8;
			__RO	uint32_t	DMARATE_RD_RES_8	:1;
			__RO	uint32_t	DMARATE_RD_RES_9	:1;
			__RO	uint32_t	DMARATE_RD_RES_10	:1;
			__RO	uint32_t	DMARATE_RD_RES_11	:1;
			__RO	uint32_t	DMARATE_RD_RES_12	:1;
			__RO	uint32_t	DMARATE_RD_RES_13	:1;
			__RO	uint32_t	DMARATE_RD_RES_14	:1;
			__RO	uint32_t	DMARATE_RD_RES_15	:1;
			__RO	uint32_t	DMARATE_RD_RES_16	:1;
			__RO	uint32_t	DMARATE_RD_RES_17	:1;
			__RO	uint32_t	DMARATE_RD_RES_18	:1;
			__RO	uint32_t	DMARATE_RD_RES_19	:1;
			__RO	uint32_t	DMARATE_RD_RES_20	:1;
			__RO	uint32_t	DMARATE_RD_RES_21	:1;
			__RO	uint32_t	DMARATE_RD_RES_22	:1;
			__RO	uint32_t	DMARATE_RD_RES_23	:1;
			__RO	uint32_t	DMARATE_RD_RES_24	:1;
			__RO	uint32_t	DMARATE_RD_RES_25	:1;
			__RO	uint32_t	DMARATE_RD_RES_26	:1;
			__RO	uint32_t	DMARATE_RD_RES_27	:1;
			__RO	uint32_t	DMARATE_RD_RES_28	:1;
			__RO	uint32_t	DMARATE_RD_RES_29	:1;
			__RO	uint32_t	DMARATE_RD_RES_30	:1;
			__RW	uint32_t	RATE_RD_ACCESS_CNT_EN	:1;
		};
	};

	union
	{
		/* Name:	DMARATE_WR
		 * Offset:	0xF8
		 * Size:	32 bits */
		__RW	uint32_t	DMARATE_WR;
		struct
		{
			__RW	uint32_t	RATE_WR_ACCESS_CNT	:8;
			__RO	uint32_t	DMARATE_WR_RES_8	:1;
			__RO	uint32_t	DMARATE_WR_RES_9	:1;
			__RO	uint32_t	DMARATE_WR_RES_10	:1;
			__RO	uint32_t	DMARATE_WR_RES_11	:1;
			__RO	uint32_t	DMARATE_WR_RES_12	:1;
			__RO	uint32_t	DMARATE_WR_RES_13	:1;
			__RO	uint32_t	DMARATE_WR_RES_14	:1;
			__RO	uint32_t	DMARATE_WR_RES_15	:1;
			__RO	uint32_t	DMARATE_WR_RES_16	:1;
			__RO	uint32_t	DMARATE_WR_RES_17	:1;
			__RO	uint32_t	DMARATE_WR_RES_18	:1;
			__RO	uint32_t	DMARATE_WR_RES_19	:1;
			__RO	uint32_t	DMARATE_WR_RES_20	:1;
			__RO	uint32_t	DMARATE_WR_RES_21	:1;
			__RO	uint32_t	DMARATE_WR_RES_22	:1;
			__RO	uint32_t	DMARATE_WR_RES_23	:1;
			__RO	uint32_t	DMARATE_WR_RES_24	:1;
			__RO	uint32_t	DMARATE_WR_RES_25	:1;
			__RO	uint32_t	DMARATE_WR_RES_26	:1;
			__RO	uint32_t	DMARATE_WR_RES_27	:1;
			__RO	uint32_t	DMARATE_WR_RES_28	:1;
			__RO	uint32_t	DMARATE_WR_RES_29	:1;
			__RO	uint32_t	DMARATE_WR_RES_30	:1;
			__RW	uint32_t	RATE_WR_ACCESS_CNT_EN	:1;
		};
	};

	union
	{
		/* Name:	DMADPRAMEDC
		 * Offset:	0xFC
		 * Size:	32 bits */
		__RW	uint32_t	DMADPRAMEDC;
		struct
		{
			__RW	uint32_t	P_DPRAM_EDC_ERR	:1;
			__RO	uint32_t	DMADPRAMEDC_RES_1	:1;
			__RO	uint32_t	DMADPRAMEDC_RES_2	:1;
			__RO	uint32_t	DMADPRAMEDC_RES_3	:1;
			__RO	uint32_t	DMADPRAMEDC_RES_4	:1;
			__RO	uint32_t	DMADPRAMEDC_RES_5	:1;
			__RO	uint32_t	DMADPRAMEDC_RES_6	:1;
			__RO	uint32_t	DMADPRAMEDC_RES_7	:1;
			__RO	uint32_t	DMADPRAMEDC_RES_8	:1;
			__RO	uint32_t	DMADPRAMEDC_RES_9	:1;
			__RO	uint32_t	DMADPRAMEDC_RES_10	:1;
			__RO	uint32_t	DMADPRAMEDC_RES_11	:1;
			__RO	uint32_t	DMADPRAMEDC_RES_12	:1;
			__RO	uint32_t	DMADPRAMEDC_RES_13	:1;
			__RO	uint32_t	DMADPRAMEDC_RES_14	:1;
			__RO	uint32_t	DMADPRAMEDC_RES_15	:1;
			__RW	uint32_t	EDC_A	:9;
			__RO	uint32_t	DMADPRAMEDC_RES_25	:1;
			__RO	uint32_t	DMADPRAMEDC_RES_26	:1;
			__RO	uint32_t	DMADPRAMEDC_RES_27	:1;
			__RO	uint32_t	DMADPRAMEDC_RES_28	:1;
			__RO	uint32_t	DMADPRAMEDC_RES_29	:1;
			__RO	uint32_t	DMADPRAMEDC_RES_30	:1;
			__RW	uint32_t	EDC_ENABLE	:1;
		};
	};

	/* Name:	DMA_COMMON_RES_0x100
	 * Offset:	0x100 - 0x7FF
	 * Size:	448 * 32 bits */
	__RO	uint32_t	DMA_COMMON_RES_0x100_0x7FC[448];

	/* Name:	DMADESMEM
	 * Offset:	0x800
	 * Size:	128 * 4 * 32 bits */
	__RW	DMAC_Descriptor_t	DMADESMEM[128];

} DMAC_Common_t;

typedef enum
{
	DMAC_ADDRESS_FIXED,
	DMAC_ADDRESS_INCREASE,
	DMAC_ADDRESS_DECREASE
	
} AddressMode_t;

typedef enum
{
	DMAC_TRANSFER_SIZE_1B = 0,
	DMAC_TRANSFER_SIZE_2B = 1,
	DMAC_TRANSFER_SIZE_4B = 2,
	DMAC_TRANSFER_SIZE_8B = 7,
	DMAC_TRANSFER_SIZE_16B = 3,
	DMAC_TRANSFER_SIZE_32B = 4,
	DMAC_TRANSFER_SIZE_64B = 5

} TransferSize_t;

typedef enum
{
	DMAC_AUTO_REQUEST = 4,
	DMAC_EXTERNAL_REQUEST = 8
	
} RequestType_t;

typedef struct
{
	uint32_t SourceAddress;
	AddressMode_t SourceAddressMode;
	uint32_t DestinationAddress;
	AddressMode_t DestinationAddressMode;
	uint32_t TransferCount;
	TransferSize_t TransferSize;
	bool InterruptEnable;
	
} DMAC_AutoTransferConfig_t;

extern void DMAC_checkRegsAddress(DMAC_Channel_t *dmac);
extern void DMAC_initDescriptorMemory(DMAC_Common_t *dmac, uint8_t stage);
extern void DMAC_configAutoTransfer(DMAC_Channel_t *dmac, DMAC_AutoTransferConfig_t *config);
extern void DMAC_enableChannel(DMAC_Channel_t *dmac);
extern void DMAC_disableChannel(DMAC_Channel_t *dmac);
extern void DMAC_enable(DMAC_Common_t *dmac);
extern void DMAC_disable(DMAC_Common_t *dmac);

#endif /* DMAC_H_ */
